export { default as Accordion } from "./mdx/Accordion.astro";
export { default as Accordions } from "./mdx/Accordions.astro";
export { default as Callout } from "./mdx/Callout.astro";
export { default as Card } from "./mdx/Card.astro";
export { default as Cards } from "./mdx/Cards.astro";
export { default as Step } from "./mdx/Step.astro";
export { default as Steps } from "./mdx/Steps.astro";
export { default as Tab } from "./mdx/Tab.astro";
export { default as Tabs } from "./mdx/Tabs.astro";
